# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-29 18:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.FileField(upload_to=mailer.models.user_directory_path_for_EmailTemplate)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('group_push_date', models.DateTimeField(auto_now_add=True)),
                ('delay_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.SmallIntegerField(default=0)),
                ('first_view_data', models.DateTimeField(blank=True, null=True)),
                ('identificator', models.UUIDField(blank=True, null=True)),
                ('push_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.PushAction')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.BooleanField(default=False)),
                ('group_name', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=mailer.models.user_directory_path_for_SubscribersCollection)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subscriberscollection',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.SubscribersGroup'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.ManyToManyField(to='mailer.SubscribersGroup'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushedmessage',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.Subscriber'),
        ),
        migrations.AddField(
            model_name='pushaction',
            name='pushed_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.SubscribersGroup'),
        ),
        migrations.AddField(
            model_name='pushaction',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailer.EmailTemplate'),
        ),
    ]
