# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-26 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='group',
            field=models.ManyToManyField(to='mailer.Group'),
        ),
    ]
