# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-30 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushedmessage',
            name='status',
            field=models.CharField(choices=[('ready', '\u041d\u0435 \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u044f\u043b\u043e\u0441\u044c'), ('success', '\u0423\u0441\u043f\u0435\u0448\u043d\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e'), ('error', '\u041e\u0448\u0438\u0431\u043a\u0430')], default='ready', max_length=100),
        ),
    ]
