# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-03-26 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0002_auto_20220326_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='group',
            field=models.ManyToManyField(to='mailer.SubscribersGroup'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
